Repository AKD-01/blogweet, pull requests merged in 2023-06, with the labels that each got.

#339 Scroll bar
  .gitpod.yml
  src/App.css
Labels: gssoc23, gssoc-accepted, level2

#263 made changes in the blog section
  package-lock.json
  package.json
  src/App.css
  src/pages/Blogpost.js
  src/pages/Contact.css
  src/pages/Home.css
  src/pages/pages.css
Labels: gssoc23, gssoc-accepted, level2

#364 placeholder added
  src/pages/Contact.js
Labels: gssoc23, level1, gssoc-accepted

#277 added a option for user to edit their post content
  package-lock.json
  package.json
  src/pages/Home.css
  src/pages/Home.js
Labels: gssoc23, gssoc-accepted, level3

#384 Fixes #326
  README.md
Labels: gssoc23, level1, gssoc-accepted

#378 Avoid Blank Posts and Add Default Photo #50
  package-lock.json
  src/App.css
  src/pages/CreatePost.js
  src/pages/Modal.js
  src/utils/firebase.js
Labels: gssoc23, gssoc-accepted, level2
