Repository AKD-01/blogweet, pull requests merged in 2023-05, with the labels that each got.

#79 [Fix]: Main content overlaps the sidebar
  src/App.css
Labels: gssoc23, level1

#88 Fixed issue #48 to add feature to scroll to top [GSSOC'23]
  package-lock.json
  package.json
  src/pages/Home.css
  src/pages/Home.js
Labels: gssoc23, gssoc-accepted, level2

#103 fixing the extra space in the attribute value
  public/index.html
Labels: gssoc23, level1, gssoc-accepted

#139 minor UI change
  src/pages/UserInfo.css
Labels: gssoc23, level1, gssoc-accepted

#113 Add 404 Not found page
  src/App.js
  src/index.js
  src/pages/Blogpost.js
  src/pages/Home.js
  src/pages/NotFound404.js
  src/pages/UserInfo.js
  src/pages/error.css
Labels: gssoc23, gssoc-accepted, level3

#152 contactpage added
  src/App.js
  src/components/SidebarOnDesktop/SidebarOnDesktop.js
  src/pages/Contact.css
  src/pages/Contact.js
Labels: gssoc23, gssoc-accepted, level3

#174 changed signin and signout function with async await syntax
  package-lock.json
  src/App.js
  src/pages/Login.js
Labels: gssoc23, gssoc-accepted, level2

#194 add contributors graph
  README.md
Labels: gssoc23, level1, gssoc-accepted

#205 added minimum 20 words limit in post
  src/pages/CreatePost.js
Labels: gssoc23, gssoc-accepted, level2

#211 [PR: Closes #132]
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/Pull_Request_Template.md
Labels: gssoc23, gssoc-accepted, level2

#213 prevent reloading of page after deletion issue no:-#212 and #207
  src/components/Card.js
  src/components/Card.module.css
  src/model_overlays/Edit.js
  src/model_overlays/Edit.module.css
  src/pages/Home.css
  src/pages/Home.js
Labels: gssoc23, gssoc-accepted, level3

#221 feat: implement authentication before post
  src/pages/CreatePost.js
Labels: gssoc23, gssoc-accepted, level2

#227 Solved issue #198 : Fixed multiple toast display
  src/pages/Home.js
Labels: gssoc23, gssoc-accepted, level2

#241 login page issue resolve
  src/components/LoginButton/index.css
  src/components/LoginButton/index.js
  src/pages/Login.js
Labels: gssoc23, level1, gssoc-accepted

#242 Improved Home Page Post UI and Responsive Sidebar Display - fixes #195
  src/App.css
  src/App.js
  src/pages/Contact.css
  src/pages/Home.css
  src/pages/Home.js
Labels: gssoc23, gssoc-accepted, level3
